openapi: 3.0.0
info:
  title: Short Url
  description: Short Url Api's collection.
  version: 0.1.9

servers:
  - url: https://shorturl-backend-vo35.onrender.com/
  - url: http://localhost:9000/

paths:
  /api/register:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User Created

  /api/login:
    post:
      summary: User Login Api.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User Login and get a token

  /api/url:
    post:
      summary: Creates a shortUrl from complete url.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        "200":
          description: Created
    security:
      - authorization: []

  /api/{shortUrl}:
    get:
      summary: Returns complete url
      parameters:
        - name: shortUrl
          in: path
          required: true
          description: Shorturl.
          schema:
            type: string
            minimum: 1
      responses:
        "200":
          description: OK

  /api/details/{page}:
    get:
      summary: Returns a list of complete urls with pagination
      parameters:
        - name: page
          in: path
          required: true
          description: page Number.
          schema:
            type: integer
      responses:
        "200":
          description: OK
    security:
      - authorization: []

  /api/url-details/{id}:
    get:
      summary: Returns data about the specified id url
      parameters:
        - name: id
          in: path
          required: true
          description: url Id.
          schema:
            type: string
      responses:
        "200":
          description: OK
    security:
      - authorization: []