openapi: 3.0.0
info:
  title: Short Url
  description: Short Url Api's collection.
  version: 0.1.9

servers:
  - url: https://shorturl-backend-vo35.onrender.com/
  # - url: http://localhost:9000/

tags:
  - name: Public APIs
    description: APIs that do not require authorization
  - name: Authorized APIs
    description: APIs that require authorization

paths:
  /api/register:
    post:
      summary: To create a new user.
      tags:
        - Public APIs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User Created
        "203":
          description: User Already Registered
        "400":
          description: UnAuthorized
        "500":
          description: Internal Server Error 

  /api/login:
    post:
      summary: User Login Api.
      tags:
        - Public APIs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User Login and get a token
        "201":
          description: Incorrect password
        "203":
          description: User Not Registered
        "400":
          description: UnAuthorized
        "500":
          description: Internal Server Error 
          
  /api/{shortUrl}:
    get:
      summary: Returns complete url from short url
      tags:
        - Public APIs
      parameters:
        - name: shortUrl
          in: path
          required: true
          description: Shorturl.
          schema:
            type: string
            minimum: 1
      responses:
        "200":
          description: Return short Url
        "201":
          description: No Url Exists
        "400":
          description: UnAuthorized
        "500":
          description: Internal Server Error 


  /api/url:
    post:
      summary: Creates a shortUrl from complete url.
      tags:
        - Authorized APIs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        "200":
          description: Return short Url
        "201":
          description: Invalid url
        "400":
          description: UnAuthorized
        "500":
          description: Internal Server Error 
    security:
      - authorization: []

  /api/details/{page}:
    get:
      summary: Returns a list of complete urls with pagination
      tags:
        - Authorized APIs
      parameters:
        - name: page
          in: path
          required: true
          description: page Number.
          schema:
            type: integer
      responses:
        "200":
          description: get the data of a page
        "500":
          description: Internal Server Error
    security:
      - authorization: []

  /api/url-details/{id}:
    get:
      summary: Returns data about the specified id url
      tags:
        - Authorized APIs
      parameters:
        - name: id
          in: path
          required: true
          description: url Id.
          schema:
            type: string
      responses:
        "200":
          description: get details of a specified id
        "500":
          description: Internal Server Error
    security:
      - authorization: []